# Lecture 3 - Linux command line and directories, and numpy arrays

In this lecture, we will be discussing the essentials of the Linux command line, linux directories, and a very useful type of Python data object called a numpy array.

To download this jupyter notebook on Roar collab, go to RC Shell Access, enter the lectures directory with `cd lectures`, and then enter the command\
`curl -O https://raw.githubusercontent.com/PsuAstro410/psuastro410.github.io/main/lectures/lec3.ipynb`\

To accept this assignment on Classroom 50 with your GitHub profile enrolled in the class, click on the link\
[https://classroom50.org/PsuAstro410/410astro26/assignments/lecture-3/accept](https://classroom50.org/PsuAstro410/410astro26/assignments/lecture-3/accept)\
and follow the steps the webpage prompts.

To submit this assignment, follow the steps in "First time Classroom 50 setup" and "Accepting and Submitting Assignments" on the course webpage:
[https://psuastro410.github.io/tips/github/](https://psuastro410.github.io/tips/github/)

### Resources and Acknowledgements

We use material from the following websites:\
https://ubuntu.com/tutorials/command-line-for-beginners#4-creating-folders-and-files\
https://arcca.github.io/An-Introduction-to-Linux-with-Command-Line/02-filedir/index.html\

and the Numpy user guide:\
https://numpy.org/doc/stable/user/absolute_beginners.html

## Linux command line and directory

During the formative years of the computer industry, one of the early operating systems was called Unix. These terminals were pretty basic by modern standards: just a keyboard and screen, with no power to run programs locally. Instead they would just send keystrokes to the server and display any data they received on the screen. There was no mouse, no fancy graphics, not even any choice of colour. Any programs that ran on the mainframe had to produce text as an output and accept text as an input. Compared with graphics, text is very light on resources, one reason why this text interface is still widely used today.

When logged into a Unix mainframe via a terminal users still had to manage the sort of file management tasks that you might now perform with a mouse and a couple of windows. Whether creating files, renaming them, putting them into subdirectories or moving them around on disk, users in the 70s could do everything entirely with a textual interface. Each of these tasks required its own program or command: one to change directories (`cd`), another to list their contents (`ls`), a third to rename or move files (`mv`), and so on. 

Linux is a sort-of-descendent of Unix. The core part of Linux is designed to behave similarly to a Unix system, such that most of the old shells and other text-based programs run on it quite happily. These days it’s far more common to use a software terminal: that same old Unix-style text interface, but running in a window alongside your graphical programs.

### Where you are: Print Working Directory

Once you open a terminal, either using the Roar Collab access terminal, or a terminal in your interactive session, you are likely at your home directory. Enter
```
pwd
```
and hit `enter`, which should return 
```
/storage/home/
```
The command itself `pwd` is an abbreviation of "print working directory", which is the default location in which any file operations will take place. If you try to create new files or directories, view existing files, or even delete them, the shell will assume you’re looking for them in the current working directory unless you take steps to specify otherwise.

### Changing your Location: Change Directory

So how do change the working directory to, say, `lectures`, which we created as a part of the first homework assignment? We use the "change directory" command `cd`:
```
cd lectures
```
verify we are in this new directory by typing
```
pwd
```
We should now see we are at `/storage/home/jxz224/lectures`. 

### Showing Directory Contents

You can show directory contents with the "list" command:
```
ls
```
This should have the new directories created when you accepted lecture assignments and cloned the class GitHub repo: these will get much simpler from now on, my first pass did things that were very complicated...

### Going Home


To move back to your home directory, type
```
cd ..
```
and you will return home. You can also type
```
cd ~
```
in *any* directory, and that will always point you all the way home.

### Moving up multiple directories

To go up multiple directories, e.g. the new directory you created when you accepted and cloned the Astro410 GitHub repo with Classroom 50, do the commands
```
cd lectures/<Classroom 50 lecture 1 directory>
```
and hit
```
ls
```
to display the contents. There is a lot of stuff here, which is my bad honestly.

### Make a new directory

Lets go back to the home directory with `cd ~`, and make a new empty directory called `useless` with the "make directory" command:
```
mkdir useless
```
This will create the empty directory `useless` with nothing in it.

### Moving files between directories

Now, lets go into `useless`, print some script, and re-direct them into a few text files:
```
echo "test script 1" > test_1.txt
echo "test script 2" > test_2.txt
echo "test script 3" > test_3.txt
```
Lets use `cat` to view both the file contents:
```
cat test_1.txt test_2.txt test_3.txt
```

Now, lets say we want to move these files to a new subdirectory of `useless`, which we create, called `more_useless`:
```
mkdir more_useless
```
We can move all these text files to `more_useless` using the "move" command:
```
mv test*.txt more_useless
```
Here, `*` is a "wildcard" command, which means "include all files which match the beginning and end of this text statement, and ignore those which don't". Now display the contents of your current directory, then move to this new directory and display its contents:
```
ls
cd more_useless
ls
```
The test files have been moved.

### Removing Files and Directories: **USE EXTREME CAUTION**

By the names of the files and directories, it is clear we don't want them to keep them. We can get rid of them with the "remove" command `rm`. However, **use extreme caution** when using this command: unlike deleting files on a graphics interface, the command line never asks "Are you *sure* you want to delete this file?"

Lets test this out: lets first delete `test_1.txt`:
```
rm test_1.txt
```
and display the directory contents again with `ls`. We see `text_1.txt` is now totally gone!

Lets live very dangerously (**BE EXTREMELY CAREFULL WITH THESE COMMANDS**) and get rid of the other two files:
```
rm test*.txt
```
Print `ls`, and we got rid of the other two files as well!

Now lets go back home with `cd ~`, and try removing `useless` with the command
```
rm useless
```
Linux comes up with an error, because `useless` is a directory. We can get rid of useless by adding the "recursive" specifier, telling linux to get rid of directories and their contents too:
```
rm -r useless
```
Enter `ls`, and we see that the contents are gone.

### Course directory structure

It is up to the student to organize their files as they see fit, but I recommend that students keep personal lecture files in a directory called `lectures`, and completed homeworks in a file `homeworks`.

## Numpy Arrays

Python lists are excellent, general-purpose containers. They can be
"heterogeneous", meaning that they can contain elements of a variety of types,
and they are quite fast when used to perform individual operations on a handful
of elements.

Depending on the characteristics of the data and the types of operations that
need to be performed, other containers may be more appropriate; by exploiting
these characteristics, we can improve speed, reduce memory consumption, and
offer a high-level syntax for performing a variety of common processing tasks.
NumPy shines when there are large quantities of "homogeneous" (same-type) data
to be processed on the CPU.

In computer programming, an array is a structure for storing and retrieving
data. We often talk about an array as if it were a grid in space, with each
cell storing one element of the data. For instance, if each element of the
data were a number, we might visualize a "one-dimensional" array like a
list:

$$
    \begin{array}{|c||c|c|c|}
    \hline
    1 & 5 & 2 & 0 \\
    \hline
    \end{array}
$$

A two-dimensional array would be like a table:

$$
    \begin{array}{|c||c|c|c|}
    \hline
    1 & 5 & 2 & 0 \\
    \hline
    8 & 3 & 6 & 1 \\
    \hline
    1 & 7 & 2 & 9 \\
    \hline
    \end{array}
$$

A three-dimensional array would be like a set of tables, perhaps stacked
as though they were printed on separate pages. In NumPy, this idea is
generalized to an arbitrary number of dimensions, and so the fundamental
array class is called ``ndarray``: it represents an "N-dimensional
array".

Most NumPy arrays have some restrictions. For instance:

- All elements of the array must be of the same type of data.
- Once created, the total size of the array can't change.
- The shape must be "rectangular", not "jagged"; e.g., each row of
  a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to
make the array faster, more memory efficient, and more convenient to use than
less restrictive data structures.

For the remainder of this document, we will use the word "array" to refer to
an instance of ``ndarray``.

Below we import numpy: almost every exercise for the rest of the course will use this Module, it is generally good to include this at the top of any code

In [1]:
import numpy as np

### Array fundamentals

One way to initialize an array is using a Python sequence, such as a list.
For example::

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

Elements of an array can be accessed in [various ways](https://numpy.org/doc/stable/user/quickstart.html#quickstart-indexing-slicing-and-iterating). For instance, we can access an
individual element of this array as we would access an element in the original
list: using the integer index of the element within square brackets.

In [3]:
a[0]

1

As with built-in Python sequences, NumPy arrays are "0-indexed": the first element of the array is accessed using index ``0``, not ``1``. Like the original list, the array is mutable.

In [4]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

Also like the original list, Python slice notation can be used for indexing.

In [5]:
a[:3]

array([10,  2,  3])

One major difference is that slice indexing of a list copies the elements into
a new list, but slicing an array returns a *view*: an object that refers to the
data in the original array. The original array can be mutated using the view.

In [7]:
b = a[3:]
b

array([4, 5, 6])

In [8]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

Two- and higher-dimensional arrays can be initialized from nested Python
sequences:

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Another difference between an array and a list of lists is that an
element of the array can be accessed by specifying the index along each
axis within a *single* set of square brackets, separated by commas.
For instance, the element ``8`` is in row ``1`` and column ``3``:

In [10]:
a[1, 3]

8

### Array attributes

The number of dimensions of an array is contained in the ``ndim`` attribute.

In [11]:
a.ndim

2

The shape of an array is a tuple of non-negative integers that specify the
number of elements along each dimension.

In [12]:
a.shape

(3, 4)

In [13]:
len(a.shape) == a.ndim

True

The fixed, total number of elements in array is contained in the ``size``
attribute.

In [14]:
a.size

12

In [15]:
import math
a.size == math.prod(a.shape)

True

Arrays are typically "homogeneous", meaning that they contain elements of
only one "data type". The data type is recorded in the ``dtype`` attribute.

In [16]:
a.dtype

dtype('int64')

### Creating Arrays

Besides creating an array from a sequence of elements, you can easily create an
array filled with ``0``'s:

In [17]:
np.zeros(2)

array([0., 0.])

Or an array filled with ``1``'s:

In [18]:
np.ones(2)

array([1., 1.])

The analogous command for python's range in numpy is `np.arange()`:

In [21]:
np.arange(4)

array([0, 1, 2, 3])

A very common command is to use ``np.linspace()`` to create an array with values that are
spaced linearly in a specified interval:

In [22]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

The command `np.logspace(a, b, num)` creates a logspace array, starting from $10^a$, and ending at $10^b$

In [23]:
np.logspace(1, 4, num=5)

array([   10.        ,    56.23413252,   316.22776602,  1778.27941004,
       10000.        ])

### Adding, removing, and sorting elements

Sorting an array is simple with ``np.sort()``. You can specify the axis, kind,
and order when you call the function.

If you start with this array:

In [24]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

You can quickly sort the numbers in ascending order with::

In [25]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

You can also join, or "concatenate", two arrays with ``np.concatenate()``:

In [26]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

You can also concotenate multimentional arrays, see [documentation](https://numpy.org/doc/2.5/reference/generated/numpy.concatenate.html)

### Slicing and Indexing

You can easily create a new array from a section of an existing array by slicing it. The below grabs a section of your array from index position 3 through index
position 8, but not including position 8 itself.

In [28]:
a = np.arange(10)
arr1 = a[3:8]
print(a, arr1)

[0 1 2 3 4 5 6 7 8 9] [3 4 5 6 7]


You can use the ``view`` method to create a new array object that looks at the
same data as the original array (a *shallow copy*).

Views are an important NumPy concept! NumPy functions, as well as operations
like indexing and slicing, will return views whenever possible. This saves
memory and is faster (no copy of the data has to be made). However it's
important to be aware of this - modifying data in a view also modifies the
original array!

Let's say you create this array::

In [29]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Now we create an array ``b1`` by slicing ``a`` and modify the first element of
``b1``. This will modify the corresponding element in ``a`` as well!

In [30]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [32]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [33]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Using the ``copy`` method will make a complete copy of the array and its data (a
*deep copy*). To use this on your array, you could run:

In [34]:
b2 = a.copy()

Below are some other ways to index and clice NumPy arrays, which are very similar to the ways to might clice a python list:

In [35]:
data = np.array([1, 2, 3])

In [36]:
data[1]

2

In [37]:
data[0:2]

array([1, 2])

In [38]:
data[1:]

array([2, 3])

In [39]:
data[-2:]

array([2, 3])

Below is a way to visualize these operations:

![indexing/slicing](https://numpy.org/doc/stable/_images/np_indexing.png)

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

For example, lets say we want to print all values of an array that are less than five. Below is some code that does this nicly with NumPy:

In [40]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


You can select elements that are divisible by 2:

In [41]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


Or you can select elements that satisfy two conditions using the `&` and `|` operators:

In [42]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


You can also make use of the logical operators `&` and `|` in order to return boolean values that specify whether or not the values in an array fulfill a certain condition. This can be useful with arrays that contain names or other categorical values.

In [43]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


### Basic Array Operations

Once you’ve created your arrays, you can start to work with them. Let’s say, for example, that you’ve created two arrays, one called “data” and one called “ones”

![array_operations_setup](https://numpy.org/doc/stable/_images/np_array_dataones.png)

You can add the arrays together with the plus sign.

In [45]:
data = np.array([1, 2])
ones = np.ones(2, dtype=np.int_)
data + ones

array([2, 3])

![operations_add_example](https://numpy.org/doc/stable/_images/np_data_plus_ones.png)

Numpy also supports subtraction, multiplication, and division:

In [46]:
data - ones

array([0, 1])

In [47]:
data * data

array([1, 4])

In [48]:
data / data

array([1., 1.])

![numpy_other_operations](https://numpy.org/doc/stable/_images/np_data_plus_ones.png)

Basic operations are simple with NumPy. If you want to find the sum of the elements in an array, you’d use sum(). This works for 1D arrays, 2D arrays, and arrays in higher dimensions.

In [49]:
a = np.array([1, 2, 3, 4])
a.sum()

10

It is also easy to find the min and max of a NumPy array:

In [50]:
a.min()

1

In [51]:
a.max()

4

### Broadcasting

There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers. You can perform this operation with:

In [52]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

![broadcasting_multiplication](https://numpy.org/doc/stable/_images/np_multiply_broadcasting.png)

NumPy understands that the multiplication should happen with each cell. That concept is called broadcasting. Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1. If the dimensions are not compatible, you will get a ValueError.

You can do these arithmetic operations on matrices of different sizes, but only if one matrix has only one column or one row. In this case, NumPy will use its broadcast rules for the operation.

In [53]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

![broadcast_multi](https://numpy.org/doc/stable/_images/np_matrix_broadcasting.png)

### Universal Functions

Universal functions work element-by-element. Let’s create an array `a`, and rescale the new array by pi / 12

In [55]:
a = np.arange(12).reshape(3,4)
b = a*np.pi/12.0
b

array([[0.        , 0.26179939, 0.52359878, 0.78539816],
       [1.04719755, 1.30899694, 1.57079633, 1.83259571],
       [2.0943951 , 2.35619449, 2.61799388, 2.87979327]])

Many numpy functions work element-by-element on arrays, such as the NumPy trig functions:

In [56]:
c = np.cos(b)
c

array([[ 1.00000000e+00,  9.65925826e-01,  8.66025404e-01,
         7.07106781e-01],
       [ 5.00000000e-01,  2.58819045e-01,  6.12323400e-17,
        -2.58819045e-01],
       [-5.00000000e-01, -7.07106781e-01, -8.66025404e-01,
        -9.65925826e-01]])